// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/etn": {
    params: {};
  };
  "/etn/pnl": {
    params: {};
  };
  "/etn/realtime": {
    params: {};
  };
  "/etn/holdings": {
    params: {};
  };
  "/management": {
    params: {};
  };
  "/management/cash-control": {
    params: {};
  };
  "/management/fees-adjustments": {
    params: {};
  };
  "/management/reconciliation-workbench": {
    params: {};
  };
  "/management/valuation-oversight": {
    params: {};
  };
  "/research/market-overview": {
    params: {};
  };
  "/research/signals": {
    params: {};
  };
  "/operations/risk": {
    params: {};
  };
  "/market-making/monitor": {
    params: {};
  };
  "/operations/blotter": {
    params: {};
  };
  "/operations/team": {
    params: {};
  };
  "/operations/preferences": {
    params: {};
  };
  "/options/realtime": {
    params: {};
  };
  "/options/risk-dashboard": {
    params: {};
  };
  "/options/strategy-lab": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/etn" | "/etn/pnl" | "/etn/realtime" | "/etn/holdings" | "/management" | "/management/cash-control" | "/management/fees-adjustments" | "/management/reconciliation-workbench" | "/management/valuation-oversight" | "/research/market-overview" | "/research/signals" | "/operations/risk" | "/market-making/monitor" | "/operations/blotter" | "/operations/team" | "/operations/preferences" | "/options/realtime" | "/options/risk-dashboard" | "/options/strategy-lab";
  };
  "./layout.tsx": {
    id: "layout";
    page: "/" | "/etn" | "/etn/pnl" | "/etn/realtime" | "/etn/holdings" | "/management" | "/management/cash-control" | "/management/fees-adjustments" | "/management/reconciliation-workbench" | "/management/valuation-oversight" | "/research/market-overview" | "/research/signals" | "/operations/risk" | "/market-making/monitor" | "/operations/blotter" | "/operations/team" | "/operations/preferences" | "/options/realtime" | "/options/risk-dashboard" | "/options/strategy-lab";
  };
  "./pages/main.tsx": {
    id: "pages/main";
    page: "/";
  };
  "./pages/etn/main.tsx": {
    id: "pages/etn/main";
    page: "/etn";
  };
  "./pages/etn/pnl.tsx": {
    id: "pages/etn/pnl";
    page: "/etn/pnl";
  };
  "./pages/etn/realtime.tsx": {
    id: "pages/etn/realtime";
    page: "/etn/realtime";
  };
  "./pages/etn/holdings.tsx": {
    id: "pages/etn/holdings";
    page: "/etn/holdings";
  };
  "./pages/management/overview.tsx": {
    id: "pages/management/overview";
    page: "/management";
  };
  "./pages/management/cash-control.tsx": {
    id: "pages/management/cash-control";
    page: "/management/cash-control";
  };
  "./pages/management/fees-adjustments.tsx": {
    id: "pages/management/fees-adjustments";
    page: "/management/fees-adjustments";
  };
  "./pages/management/reconciliation-workbench.tsx": {
    id: "pages/management/reconciliation-workbench";
    page: "/management/reconciliation-workbench";
  };
  "./pages/management/valuation-oversight.tsx": {
    id: "pages/management/valuation-oversight";
    page: "/management/valuation-oversight";
  };
  "./pages/research/market-overview.tsx": {
    id: "pages/research/market-overview";
    page: "/research/market-overview";
  };
  "./pages/research/signals.tsx": {
    id: "pages/research/signals";
    page: "/research/signals";
  };
  "./pages/operations/risk.tsx": {
    id: "pages/operations/risk";
    page: "/operations/risk";
  };
  "./pages/market-making/monitor.tsx": {
    id: "pages/market-making/monitor";
    page: "/market-making/monitor";
  };
  "./pages/operations/blotter.tsx": {
    id: "pages/operations/blotter";
    page: "/operations/blotter";
  };
  "./pages/operations/team.tsx": {
    id: "pages/operations/team";
    page: "/operations/team";
  };
  "./pages/operations/preferences.tsx": {
    id: "pages/operations/preferences";
    page: "/operations/preferences";
  };
  "./pages/options/realtime.tsx": {
    id: "pages/options/realtime";
    page: "/options/realtime";
  };
  "./pages/options/risk-dashboard.tsx": {
    id: "pages/options/risk-dashboard";
    page: "/options/risk-dashboard";
  };
  "./pages/options/strategy-lab.tsx": {
    id: "pages/options/strategy-lab";
    page: "/options/strategy-lab";
  };
};