// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/etn/pnl": {
    params: {};
  };
  "/etn/realtime": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/etn/pnl" | "/etn/realtime";
  };
  "./layout.tsx": {
    id: "layout";
    page: "/" | "/etn/pnl" | "/etn/realtime";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./pages/etn/pnl.tsx": {
    id: "pages/etn/pnl";
    page: "/etn/pnl";
  };
  "./pages/etn/realtime.tsx": {
    id: "pages/etn/realtime";
    page: "/etn/realtime";
  };
};